server:
  port: 8084
  servlet:
    context-path: /paymentservice
    
security:
   oauth2:
      resource:
#         userInfoUri: http://localhost:8090/authentication/resources/userinfo
         userInfoUri: http://authenticationservice:8090/authentication/resources/userinfo

#spring:
#  cloud:
#    stream:
#     bindings:
#        inboundOrgChanges:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup
#     kafka:
#        binder:
#          zkNodes: localhost
#          brokers: localhost

#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

